# Generated by Django 2.1.5 on 2019-01-20 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('speechrecognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
