# Generated by Django 2.1.5 on 2019-01-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechrecognition', '0002_voice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='audio/file/'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='file',
            field=models.FileField(upload_to='audio/file/'),
        ),
    ]
