# Generated by Django 2.2.1 on 2019-05-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechrecognition', '0004_auto_20190121_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice',
            name='description',
        ),
        migrations.AlterField(
            model_name='voice',
            name='file',
            field=models.FileField(max_length=200, upload_to='audio/file/'),
        ),
    ]
